### ISSUE TITLE
Class Feedback: Notebook 4.2: Use lowercase "x"

### ISSUE THREAD

**Issue by pllim** [CodesBay/PyCon2019#1]
Using lowercase "x" instead of uppercase would be easier to type and also more consistent with PEP 8 and the its corresponding "y".

**Comment by TheTheoryOfCode** [comment]
@pllim 

The uppercase 'X' is used to denote multi-column features, while 'y' is used for denoting a single Label, Hence the differentiation. 

It's a general trend just for a different purpose while using python programming with Machine Learning

Hope it Helps

Thanks
