### ISSUE TITLE
Class feedback: Consider using Binder

### ISSUE THREAD

**Issue by pllim** [CodesBay/PyCon2019#5]
There were some participants not using notebooks locally for whatever reasons. In another tutorial, I found that Binder with all the necessary tools set up worked well; it lowered the entry barrier by allowing those with problem getting notebook to run locally to follow along.

**Comment by TheTheoryOfCode** [comment]
@pllim 

Thanks for the valuable suggestion. Will definitely explore binder for the next time

Thanks
